### ISSUE TITLE
Crash happens on having dataset size lesser than numColumns

### ISSUE THREAD

**Issue by nikhilneela** [dgreenhalgh/simple-item-decoration#25]
Hi,

This is a really useful demo app to understand the nitty gritties of recycler view itwm decorations. I found a corner case whwere the demo crashes if the dataset size is lesser than the numColumns. Please find below the stack trace,

E/AndroidRuntime(20614): Process: com.dgreenhalgh.android.simpleitemdecorationsample, PID: 20614
E/AndroidRuntime(20614): java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.View.getLayoutParams()' on a null object reference
E/AndroidRuntime(20614):    at com.dgreenhalgh.android.simpleitemdecoration.grid.GridDividerItemDecoration.drawHorizontalDividers(GridDividerItemDecoration.java:84)
E/AndroidRuntime(20614):    at com.dgreenhalgh.android.simpleitemdecoration.grid.GridDividerItemDecoration.onDraw(GridDividerItemDecoration.java:43)
E/AndroidRuntime(20614):    at android.support.v7.widget.RecyclerView.onDraw(RecyclerView.java:3162)
E/AndroidRuntime(20614):    at android.view.View.draw(View.java:15231)
E/AndroidRuntime(20614):    at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3097)
E/AndroidRuntime(20614):    at android.view.View.updateDisplayListIfDirty(View.java:14167)
E/AndroidRuntime(20614):    at android.view.View.getDisplayList(View.java:14189)
E/AndroidRuntime(20614):    at android.view.View.draw(View.java:14959)
E/AndroidRuntime(20614):    at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
E/AndroidRuntime(20614):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
E/AndroidRuntime(20614):    at android.view.View.updateDisplayListIfDirty(View.java:14162)
E/AndroidRuntime(20614):    at android.view.View.getDisplayList(View.java:14189)
E/AndroidRuntime(20614):    at android.view.View.draw(View.java:14959)
E/AndroidRuntime(20614):    at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
E/AndroidRuntime(20614):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
E/AndroidRuntime(20614):    at android.view.View.updateDisplayListIfDirty(View.java:14162)
E/AndroidRuntime(20614):    at android.view.View.getDisplayList(View.java:14189)
E/AndroidRuntime(20614):    at android.view.View.draw(View.java:14959)
E/AndroidRuntime(20614):    at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
E/AndroidRuntime(20614):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
E/AndroidRuntime(20614):    at android.view.View.updateDisplayListIfDirty(View.java:14162)
E/AndroidRuntime(20614):    at android.view.View.getDisplayList(View.java:14189)
E/AndroidRuntime(20614):    at android.view.View.draw(View.java:14959)
E/AndroidRuntime(20614):    at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
E/AndroidRuntime(20614):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
E/AndroidRuntime(20614):    at android.view.View.updateDisplayListIfDirty(View.java:14162)
E/AndroidRuntime(20614):    at android.view.View.getDisplayList(View.java:14189)
E/AndroidRuntime(20614):    at android.view.View.draw(View.java:14959)
E/AndroidRuntime(20614):    at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
E/AndroidRuntime(20614):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
E/AndroidRuntime(20614):    at android.view.View.updateDisplayListIfDirty(View.java:14162)
E/AndroidRuntime(20614):    at android.view.View.getDisplayList(View.java:14189)
E/AndroidRuntime(20614):    at android.view.View.draw(View.java:14959)
E/AndroidRuntime(20614):    at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
E/AndroidRuntime(20614):    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
E/AndroidRuntime(20614):    at android.view.View.draw(View.java:15234)
E/AndroidRuntime(20614):    at android.widget.FrameLayout.draw(FrameLayout.java:598)
E/AndroidRuntime(20614):    at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2650)
E/AndroidRuntime(20614):    at android.view.View.updateDisplayListIfDirty(View.java:14167)
E/AndroidRuntime(20614):    at android.view.View.getDisplayList(View.java:14189)
E/AndroidRuntime(20614):    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
E/AndroidRuntime(20614):    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
E/AndroidRuntime(20614):    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
E/AndroidRuntime(20614):    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2530)
E/AndroidRuntime(20614):    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2352)
E/AndroidRuntime(20614):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
E/AndroidRuntime(20614):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
E/AndroidRuntime(20614):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
E/AndroidRuntime(20614):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
E/AndroidRuntime(20614):    at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/AndroidRuntime(20614):    at android.view.Choreographer.doFrame(Choreographer.java:550)
E/AndroidRuntime(20614):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/AndroidRuntime(20614):    at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(20614):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(20614):    at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(20614):    at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(20614):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20614):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(20614):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(20614):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by adammo1990** [comment]
I have the same problem

**Comment by dgreenhalgh** [comment]
@nikhilneela, I noted this over in the [Big Nerd Ranch fork of this repo](https://github.com/bignerdranch/simple-item-decoration/issues/28), but I'm currently working on a 2.0 version of this library that will take care of this problem. Thanks for reporting this issue!
